### ISSUE TITLE
When navigating from a quiz to the about page, the url keeps /quizzes/, thus breaking

### ISSUE THREAD

**Issue by conbainbridge** [pushkin-consortium/pushkin-sitetemplates-default#18]
When at a quiz (e.g. localhost/quizzes/quizName), if you click on about in the nav bar it ends up routing to: localhost/quizzes/about. This does not happen if you click on Findings or Quizzes.

**Comment by jkhartshorne** [comment]
just ran into this independently. You want to take a crack at it?

**Comment by conbainbridge** [comment]
Fixed thanks to one slash!

Relevant commit: https://github.com/pushkin-consortium/pushkin-sitetemplates-default/commit/abeaac63ba73955b42e50143b62cea2c9a03b4b0
