### ISSUE TITLE
Fix boilerplate for 'findings'

### ISSUE THREAD

**Issue by jkhartshorne** [pushkin-consortium/pushkin-sitetemplates-default#25]
Right now, it has several examples taken from gameswithwords.org. That's not ideal. Please replace with some Lorem Ipsum text.

Check out pushkin/front-end/src/components/FindingsData.js

Then please update `advanced/modifying-site-template/Findings/findings-page.md` as needed.

**Comment by conbainbridge** [comment]
https://github.com/pushkin-consortium/pushkin-sitetemplates-default/commit/a926ab74e47bcf14ffbec9fbbc162dcedfa25ed5
