### ISSUE TITLE
Fix boilerplate for 'people'

### ISSUE THREAD

**Issue by jkhartshorne** [pushkin-consortium/pushkin-sitetemplates-default#26]
Right now, it has people taken from gameswithwords.org. That's not ideal. Please replace with some stock photos and Lorem Ipsum text.

Check out pushkin/front-end/src/components/TeamMember/People.js

Then please update `advanced/modifying-site-template/about-page.md` as needed.

**Comment by conbainbridge** [comment]
https://github.com/pushkin-consortium/pushkin-sitetemplates-default/commit/a926ab74e47bcf14ffbec9fbbc162dcedfa25ed5
