### ISSUE TITLE
Fix size of quiz tiles on quiz list

### ISSUE THREAD

**Issue by jkhartshorne** [pushkin-consortium/pushkin-sitetemplates-default#8]
On the desktop version, they are currently too large. They should be made smaller, but in a way that will still work on mobile. Probably the number of tiles shown on a particular row should depend on screen resolution.

**Comment by hrcn** [comment]
Have you tried the latest commit I made yesterday? https://github.com/hrcn/pushkin-sitetemplates-default/commit/4f0a6b50c2a32d6236c731c6b320a88ca2c42b94

**Comment by jkhartshorne** [comment]
Looks good on the desktop. Do you know of a good way for me to preview what it would look like on mobile?

**Comment by hrcn** [comment]
You can use toggle device toolbar located in the upper left corner in Chrome console. The page doesn't look good since I didn't consider mobile supports.

**Comment by jkhartshorne** [comment]
OK. Well, please consider mobile support, then! That’s pretty important for us going forward. More and more people are using mobile devices and not desktops/laptops.
